"""
Verilog Testbench Generator - Streamlit Web Application

Main entry point for the web UI. Integrates parser, prompt builder,
generator, and demo mode into a single interactive application.
"""

import logging
import time

import streamlit as st

from parser import VerilogParser, ParseError
from prompt_builder import PromptBuilder
from generator import TestbenchGenerator, GenerationError, ValidationError
from demo_responses import get_demo_response

# ---------------------------------------------------------------------------
# Logging configuration
# ---------------------------------------------------------------------------

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s - %(name)s - %(levelname)s - %(message)s",
)
logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _check_syntax(code: str) -> list[str]:
    """
    Run basic syntax checks on generated Verilog code.

    Returns a list of warning strings (empty if no issues found).
    """
    warnings = []

    open_parens = code.count("(")
    close_parens = code.count(")")
    if open_parens != close_parens:
        warnings.append(
            f"Unbalanced parentheses detected ({open_parens} open, {close_parens} close)"
        )

    begin_count = len([w for w in code.split() if w.lower() == "begin"])
    end_count = len([w for w in code.split() if w.lower() == "end"])
    # 'endmodule' contains 'end', so subtract those
    endmodule_count = code.lower().count("endmodule")
    end_count -= endmodule_count
    if begin_count != end_count:
        warnings.append(
            f"Unbalanced begin/end blocks detected ({begin_count} begin, {end_count} end)"
        )

    return warnings


def _build_fallback_prompt(module_info) -> str:
    """Build a simplified fallback prompt for the last retry attempt."""
    ports_summary = ", ".join(
        f"{p.direction.value} {p.name}" for p in module_info.ports
    )
    return (
        f"Generate a Verilog testbench for module '{module_info.module_name}'.\n"
        f"Ports: {ports_summary}\n"
        f"Logic type: {module_info.logic_type.value}\n\n"
        "Requirements:\n"
        f"- Module name: tb_{module_info.module_name}\n"
        "- Include `timescale 1ns/1ps\n"
        "- Declare inputs as reg, outputs as wire\n"
        f"- Instantiate {module_info.module_name} as dut\n"
        "- Include basic test cases with $display and $finish\n"
        "- Output pure Verilog only, no markdown\n"
    )


def _get_api_key() -> str | None:
    """Safely retrieve the OpenAI API key from Streamlit secrets."""
    try:
        return st.secrets["OPENAI_API_KEY"]
    except (KeyError, FileNotFoundError):
        return None


# ---------------------------------------------------------------------------
# Main application
# ---------------------------------------------------------------------------


def main():
    # -----------------------------------------------------------------------
    # Page configuration
    # -----------------------------------------------------------------------
    st.set_page_config(
        page_title="Verilog Testbench Generator",
        page_icon="⚡",
        layout="wide",
    )

    st.title("⚡ Verilog Testbench Generator")
    st.write(
        "Upload or paste a Verilog RTL module and get a simulation-ready testbench "
        "generated by AI — in seconds."
    )

    # -----------------------------------------------------------------------
    # Sidebar
    # -----------------------------------------------------------------------
    with st.sidebar:
        st.header("⚙️ Settings")

        demo_mode = st.checkbox("🎭 Demo Mode (No API required)", value=False)

        if not demo_mode:
            api_key = _get_api_key()
            if api_key:
                st.success("✅ API key configured")
            else:
                st.warning("⚠️ API key not configured")
                st.caption(
                    "Add `OPENAI_API_KEY` to `.streamlit/secrets.toml` to enable generation."
                )

        model_choice = st.selectbox(
            "LLM Model",
            options=["gpt-3.5-turbo", "gpt-4"],
            index=0,
            disabled=demo_mode,
        )

        max_retries = st.selectbox(
            "Max Retries",
            options=[1, 2, 3],
            index=1,
            disabled=demo_mode,
        )

        st.divider()
        with st.expander("ℹ️ About"):
            st.markdown(
                """
**Verilog Testbench Generator** automates testbench creation for Verilog RTL modules.

**How it works:**
1. Paste or upload your Verilog module
2. The parser extracts ports and logic type
3. A structured prompt is built for the LLM
4. The LLM generates a simulation-ready testbench

**Demo Mode** uses predefined examples — no API key needed.
                """
            )

    # -----------------------------------------------------------------------
    # Input section
    # -----------------------------------------------------------------------
    st.subheader("📥 Input")

    input_method = st.radio(
        "Input method",
        options=["Upload File", "Paste Code"],
        horizontal=True,
        label_visibility="collapsed",
    )

    verilog_code = ""

    if input_method == "Upload File":
        uploaded_file = st.file_uploader(
            "Choose a Verilog file",
            type=["v", "sv"],
            label_visibility="collapsed",
        )
        if uploaded_file is not None:
            verilog_code = uploaded_file.read().decode("utf-8", errors="replace")
    else:
        verilog_code = st.text_area(
            "Paste Verilog code here",
            height=300,
            placeholder="module my_module(\n    input a,\n    output b\n);\n    assign b = a;\nendmodule",
            label_visibility="collapsed",
        )

    if verilog_code.strip():
        with st.expander("👁 Preview input code", expanded=False):
            st.code(verilog_code, language="verilog")

    # -----------------------------------------------------------------------
    # Generate button
    # -----------------------------------------------------------------------
    generate_clicked = st.button("🚀 Generate Testbench", type="primary")

    if generate_clicked:
        if not verilog_code.strip():
            st.error("Please provide Verilog code — upload a file or paste code above.")
        else:
            _run_generation(
                verilog_code=verilog_code,
                demo_mode=demo_mode,
                model_choice=model_choice,
                max_retries=max_retries,
            )

    # -----------------------------------------------------------------------
    # Results display (persisted in session_state)
    # -----------------------------------------------------------------------
    if "testbench_code" in st.session_state and st.session_state["testbench_code"]:
        _show_results()


# ---------------------------------------------------------------------------
# Generation orchestration
# ---------------------------------------------------------------------------


def _run_generation(
    verilog_code: str,
    demo_mode: bool,
    model_choice: str,
    max_retries: int,
) -> None:
    """Orchestrate the full generation pipeline and store results in session_state."""

    total_start = time.perf_counter()

    with st.spinner("Generating testbench..."):
        try:
            # --- Parse ---
            logger.info("Starting Verilog parsing")
            parse_start = time.perf_counter()
            parser = VerilogParser()
            module_info = parser.parse(verilog_code)
            parse_time = time.perf_counter() - parse_start
            logger.info(
                f"Parsing succeeded: module='{module_info.module_name}', "
                f"ports={len(module_info.ports)}, time={parse_time:.3f}s"
            )

            # --- Build prompt ---
            prompt_start = time.perf_counter()
            prompt_builder = PromptBuilder()
            prompt = prompt_builder.build_prompt(module_info)
            fallback_prompt = _build_fallback_prompt(module_info)
            prompt_time = time.perf_counter() - prompt_start
            logger.info(f"Prompt built in {prompt_time:.3f}s")

            # --- Generate ---
            logger.info(
                f"Starting generation (demo_mode={demo_mode}, model={model_choice})"
            )
            gen_start = time.perf_counter()

            if demo_mode:
                testbench_code = get_demo_response(module_info)
                logger.info("Demo mode: returned predefined testbench")
            else:
                api_key = _get_api_key()
                generator = TestbenchGenerator(api_key=api_key)
                generator.model = model_choice
                testbench_code = generator.generate(
                    prompt=prompt,
                    module_name=module_info.module_name,
                    fallback_prompt=fallback_prompt,
                )
                logger.info("Generation succeeded via API")

            gen_time = time.perf_counter() - gen_start
            total_time = time.perf_counter() - total_start

            # --- Syntax checks (Task 13) ---
            syntax_warnings = _check_syntax(testbench_code)

            # --- Store results ---
            st.session_state["testbench_code"] = testbench_code
            st.session_state["input_code"] = verilog_code
            st.session_state["module_name"] = module_info.module_name
            st.session_state["demo_mode"] = demo_mode
            st.session_state["perf"] = {
                "parse_time": parse_time,
                "prompt_time": prompt_time,
                "gen_time": gen_time,
                "total_time": total_time,
            }
            st.session_state["syntax_warnings"] = syntax_warnings

            logger.info(
                f"Total generation time: {total_time:.2f}s "
                f"(parse={parse_time:.3f}s, prompt={prompt_time:.3f}s, gen={gen_time:.3f}s)"
            )

            st.success(f"✅ Generated in {total_time:.2f} seconds")

            with st.expander("⏱ Performance Details"):
                st.write(f"- **Parse time:** {parse_time:.3f}s")
                st.write(f"- **Prompt build time:** {prompt_time:.3f}s")
                st.write(f"- **Generation time:** {gen_time:.3f}s")
                st.write(f"- **Total time:** {total_time:.2f}s")

            for w in syntax_warnings:
                st.warning(f"⚠️ Syntax check: {w}")

        except ParseError as e:
            logger.error(f"ParseError: {e}")
            st.error(
                f"**Parsing Error:** {e}\n\n"
                "Make sure your input is a valid Verilog module with a `module ... endmodule` declaration."
            )
        except ValidationError as e:
            logger.error(f"ValidationError: {e}")
            st.error(
                f"**Validation Error:** {e}\n\n"
                "The generated testbench is missing critical elements. Try again."
            )
        except GenerationError as e:
            logger.error(f"GenerationError: {e}")
            st.error(
                f"**Generation Error:** {e}\n\n"
                "Check your API key and network connection, then try again."
            )
        except Exception as e:
            logger.exception(f"Unexpected error: {e}")
            st.error(f"**Unexpected Error:** {e}")


# ---------------------------------------------------------------------------
# Results display
# ---------------------------------------------------------------------------


def _show_results() -> None:
    """Render the side-by-side results panel from session_state."""
    testbench_code = st.session_state["testbench_code"]
    input_code = st.session_state.get("input_code", "")
    module_name = st.session_state.get("module_name", "module")
    is_demo = st.session_state.get("demo_mode", False)

    st.divider()

    if is_demo:
        st.info("🎭 Demo Mode — showing a predefined testbench example")

    col1, col2 = st.columns(2)

    with col1:
        st.subheader("📄 Input Verilog")
        st.code(input_code, language="verilog")

    with col2:
        st.subheader("🧪 Generated Testbench")
        st.code(testbench_code, language="verilog")
        st.download_button(
            label="⬇️ Download Testbench (.v)",
            data=testbench_code,
            file_name=f"tb_{module_name}.v",
            mime="text/plain",
        )


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    main()
